# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables: 
    ## Add this under variables section in the pipeline
    azureSubscription: 'newman.gerard@gmail.com'
    appName: 'RESOLVER-API'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureFunctionApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: 'newman.gerard@gmail.com'
    appType: functionAppLinux
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip
  
